import mongoose from "mongoose";
import { extractTOCAndAddIds } from "../services/extractTOC.js";
import { calculateSEOScore } from "../services/seo.service.js";

/* ─────────────────────────────────────────────
   SUB-SCHEMA: single TOC entry
───────────────────────────────────────────── */
const tocEntrySchema = new mongoose.Schema(
  {
    id: {
      type: String,
      required: true,
      // Human-readable slug, doubles as HTML anchor: #getting-started
    },
    text: {
      type: String,
      required: true,
      trim: true,
      // Raw heading text with emoji/markup stripped, e.g. "Brain and Perceptrons"
    },
    level: {
      type: Number,
      required: true,
      min: 1,
      max: 6,
      // Matches H1–H6
    },
    order: {
      type: Number,
      required: true,
      // Zero-based position in document; explicit so reordering is safe
    },
  },
  { _id: false }, // TOC entries are value objects, not independent documents
);

/* ─────────────────────────────────────────────
   MAIN SCHEMA
───────────────────────────────────────────── */
const noteSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
    },

    content: {
      type: String,
      default: "",
    },

    seo: {
      title: {
        type: String,
        default: "",
      },
      description: {
        type: String,
        default: "",
      },
      keywords: {
        type: [String],
        default: [],
      },
      image: {
        url: {
          type: String,
          default: "",
        },
        alt: {
          type: String,
          default: "",
        },
      },
      score: {
        type: Number,
        default: 100,
      },
    },

    tableOfContent: {
      type: [tocEntrySchema],
      default: [],
      // Derived from `content`. Never set manually — always regenerated by middleware.
      // Flat array; reconstruct nested tree on the client using the `level` field.
    },

    collectionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Collection",
      required: true,
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    visibility: {
      type: String,
      enum: ["public", "private"],
      default: "private",
      required: true,
    },

    collaborators: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
      },
    ],

    slug: {
      type: String,
      required: true,
    },

    gsc: {
      isIndexed:  { type: Boolean, default: false },
      lastSynced: { type: Date,    default: null  },
    },

    contentUpdatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  },
);

/* ===================== NOTE MODEL INDEXES ===================== */
noteSchema.index({ collectionId: 1, slug: 1 }, { unique: true });
noteSchema.index({ collectionId: 1, createdAt: -1 });

noteSchema.index({
  collectionId: 1,
  visibility: 1,
  collaborators: 1,
  createdAt: -1,
});

noteSchema.index({
  collectionId: 1,
  visibility: 1,
  slug: 1,
});

noteSchema.index({
  collectionId: 1,
  visibility: 1,
  userId: 1,
});

noteSchema.index({
  collectionId: 1,
  visibility: 1,
  collaborators: 1,
});

noteSchema.index({
  visibility: 1,
  contentUpdatedAt: -1,
});

noteSchema.index({ "gsc.isIndexed": 1 });

/* ===================== MIDDLEWARE ===================== */

// Slug generator (MUST run before validation)
// Slug generator (MUST run before validation)
noteSchema.pre("validate", async function (next) {
  // 1. If slug is explicitly provided and not modified, skip
  // 2. If name is modified and slug is NOT explicitly modified, regenerate slug from name
  // 3. If slug is missing, generate from name

  const slugModified = this.isModified("slug");
  const nameModified = this.isModified("name");

  if (!slugModified && !nameModified && this.slug) {
    return next();
  }

  // Determine base string for slug
  let baseString = slugModified ? this.slug : this.name;
  if (!baseString) return next();

  const baseSlug = baseString
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  let slug = baseSlug;
  let counter = 1;

  while (
    await this.constructor.exists({
      collectionId: this.collectionId,
      slug,
      _id: { $ne: this._id },
    })
  ) {
    slug = `${baseSlug}-${counter++}`;
  }

  this.slug = slug;
  next();
});

// TOC and SEO score regenerator — runs only when `content` or `seo` actually changed
noteSchema.pre("save", function (next) {
  if (this.isModified("content")) {
    const { html, toc } = extractTOCAndAddIds(this.content);
    this.content = html; // persist heading IDs back to content
    this.tableOfContent = toc;
  }

  if (
    this.isModified("content") ||
    this.isModified("seo") ||
    this.isModified("name")
  ) {
    if (!this.seo) {
      this.seo = {};
    }
    this.seo.score = calculateSEOScore(this);
  }
  next();
});

const Note = mongoose.model("Note", noteSchema);
export default Note;
